export const references = {
  pageCourante: document.body?.dataset.page ?? "home",
  menuButton: document.querySelector("#menuButton"),
  menuPrincipal: document.querySelector("#menuPrincipal"),
  compteurProjets: document.querySelector("#compteurProjets"),
  etatApplication: document.querySelector("#etatApplication"),
  projetsVedette: document.querySelector("#projetsVedette"),
  listeProjets: document.querySelector("#listeProjets"),
  selectionProjets: document.querySelector("#selectionProjets"),
  detailProjet: document.querySelector("#detailProjet"),
  detailProjetVide: document.querySelector("#detailProjetVide"),
  detailCategorie: document.querySelector("#detailCategorie"),
  detailLibelle: document.querySelector("#detailLibelle"),
  detailDescription: document.querySelector("#detailDescription"),
  detailImage: document.querySelector("#detailImage"),
  detailPeriode: document.querySelector("#detailPeriode"),
  detailStatut: document.querySelector("#detailStatut"),
  detailRole: document.querySelector("#detailRole"),
  detailLien: document.querySelector("#detailLien"),
  detailTechnologies: document.querySelector("#detailTechnologies"),
  formAjoutProjet: document.querySelector("#formAjoutProjet"),
  retourFormulaire: document.querySelector("#retourFormulaire"),
  champLibelle: document.querySelector("#champLibelle"),
  champImage: document.querySelector("#champImage"),
  champCategorie: document.querySelector("#champCategorie"),
  champPeriode: document.querySelector("#champPeriode"),
  champStatut: document.querySelector("#champStatut"),
  champRole: document.querySelector("#champRole"),
  champTechnologies: document.querySelector("#champTechnologies"),
  champLien: document.querySelector("#champLien"),
  champDescription: document.querySelector("#champDescription"),
  blocExperience: document.querySelector("#blocExperience"),
  blocFormation: document.querySelector("#blocFormation"),
  blocComplementaire: document.querySelector("#blocComplementaire")
};
